Рабочая версия
Protei-Lab-Study/dotnet-telegram-notifications pull request #1
Opened 2023-04-19 10:33 UTC by mayabatman

Работа контроллера проверена через Postman. Всё работает. Возможно стоит изменить или добавить выводимую информацию в уведомлении о pipeline

2023-04-19 12:45 UTC, PLStudents commented on ProteiTelegramBot/appsettings.Development.json
> -    "HangfireConnection": "<connection_string>",
Develop-конфиги не должны меняться - их каждый разработчик выставляет по себя.
@paulrozhkin , возможно их вообще в gitignore нужно поставить.

2023-04-19 12:46 UTC, PLStudents commented on ProteiTelegramBot/ProteiTelegramBot.csproj
> +    <Compile Remove="Models\Class.cs" />
Название файла должно соответствовать названию класса

2023-04-19 12:48 UTC, PLStudents commented on ProteiTelegramBot/Models/MergeRequestEvent.cs
> +        public MergeRequestUser user { get; set; }
По рекомендациям Microsoft имена св-в должны начинаться с заглавной буквы. Если при этом автоматический резолв при десериализации не проходит, то нужно использовать атрибут `[JsonPropertyName("имя св-ва в json")]`

2023-04-19 12:50 UTC, PLStudents commented on ProteiTelegramBot/Controllers/WebHooksController.cs
> +                        MergeRequestEvent? mergeRequestEvent = JsonConvert.DeserializeObject<MergeRequestEvent>(body);
Лучше использовать `var` при инициализации переменных на случай, если возвращаемый тип изменится, например:
```csharp
var mergeRequestEvent = JsonConvert.DeserializeObject<MergeRequestEvent>(body);
```

2023-04-19 12:51 UTC, PLStudents commented on ProteiTelegramBot/Controllers/WebHooksController.cs
> +                case "pipeline":
Думаю, что тут нужно было не заменять уже существующие экшены, а добавить новые

2023-04-19 12:53 UTC, PLStudents commented on ProteiTelegramBot/Config/NotificationCronOptions.cs
> +    public int NotifyDutyAtHourUtc { get; set; } = 14;
Дефолтное значение не нужно менять

2023-04-20 06:10 UTC, paulrozhkin commented on ProteiTelegramBot/appsettings.Development.json
> -    "HangfireConnection": "<connection_string>",
Вот только они поменяются, если будет добавлен новый конфиг. Ситуация двоякая. Ченжи отменить, в gitignore пока не добавлять. Я практику подход, когда просто заполняю подобными строками `<connection_string>` и не включаю конфиги в коммит. Если есть другой отработанный способ, то будет интересно услышать.

2023-04-20 06:13 UTC, paulrozhkin commented on ProteiTelegramBot/Controllers/WebHooksController.cs
> +                case "pipeline":
Все нормально, обработка экшинов по mr перенесена в GitLabWebHookMergeRequestAsync. Просто теперь case на requestEvent.object_kind, а не на mergeRequestEvent.ObjectAttributes.Action.

2023-04-20 06:24 UTC, paulrozhkin requested changes

2023-04-20 06:24 UTC, paulrozhkin commented on ProteiTelegramBot/Controllers/WebHooksController.cs
> +            _logger.LogInformation(
Нотификации должны быть только по упавшим пайплайнам, иначе будет спам. Из задачи:
>>
При поступлении запроса, если состояние говорит об удачной сборке, нужно запустить cron по которому должна быть отправлена нотификация о том, что ветку можно мержить.

2023-04-20 06:24 UTC, paulrozhkin commented on ProteiTelegramBot/Models/Notification.cs
> +            "***⚠️ Pipeline status changed ***" +
В соответствии с тем, что нотификации будут только по упавшим, лучше изменить знак на красный и писать Pipeline failed.
Предлагаю что-то следующие:
`*** ⛔ Pipeline failed ***`

2023-04-20 06:24 UTC, paulrozhkin commented on ProteiTelegramBot/Models/Notification.cs
> +            $"[{RemoveInvalidTelegramCharacters(_title)}]({_url}) (opened by {_creator})"+
Текст дублирует открытие mr, должен быть свой.

2023-04-20 06:29 UTC, paulrozhkin commented on ProteiTelegramBot/Controllers/WebHooksController.cs
> +            _logger.LogInformation(
Ай, а тут я сам неправильно прочитал. Задачи про другое были. Ну, так или иначе, 2 и 3 пункты из задачи не реализованы.

2023-04-20 06:30 UTC, paulrozhkin commented on ProteiTelegramBot/Controllers/WebHooksController.cs
> +            _logger.LogInformation(
Но, первостепенно, нам бы видеть нотификации о падении пайплайнов. В первую очередь нужно добавить обработку именно их.

2023-04-20 06:34 UTC, paulrozhkin commented on ProteiTelegramBot/Models/Notification.cs
> +            "***⚠️ Pipeline status changed ***" +
На текущий момент можно проигнорировать

2023-04-20 06:34 UTC, paulrozhkin commented on ProteiTelegramBot/Controllers/WebHooksController.cs
> +            _logger.LogInformation(
На текущий момент можно проигнорировать

2023-04-22 08:58 UTC, mayabatman commented
Все замечания были учтены и исправлены. Вместо JsonPropertyName использовала JsonProperty, т.к. первый не работал. Уведомления о пайплайнах создаются тогда, когда статус пайплайна не равен "success". (Я не смогла узнать, чему будет равно это свойство в случае падения, но предположила, что это необязательно, ведь если не успешно, то точно что-то так)

2023-04-24 12:45 UTC, paulrozhkin requested changes

2023-04-24 12:45 UTC, paulrozhkin commented on ProteiTelegramBot/appsettings.Development.json
> +  "NotificationCron": null,
Верни как было. Сейчас NotifyDutyAtHourUtc никак не связан с NotificationCron и будет проигнорирован. Должно быть:
```
"NotificationCron": {
    "NotifyDutyAtHourUtc": 5
}
```

2023-04-26 07:26 UTC, mayabatman commented
Да, простите, это опечаточка была

2023-04-30 21:00 UTC, merged